name: "Node.js CI"

env:
  HUSKY: 0
  CI: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.13.0
      uses: actions/setup-node@v2
      with:
        node-version: 16.13.0
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run bundle --if-present
    - run: npx playwright install --with-deps
    - run: npm run test --if-present
